identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    q
  allowed_symbols: "_"


disabled_rules:
  - todo
  - trailing_comma
  - empty_enum_arguments
  - opening_brace
  - trailing_whitespace

